[project]
name = "attention-is-all-you-need"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wirtual11", email = "22962454+wirtual11@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "torch>=2.14.0",
]

[project.scripts]
attention-is-all-you-need = "attention_is_all_you_need.main:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
